# Generated by Django 4.2.1 on 2023-05-22 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livros',
            name='imagem',
            field=models.ImageField(default='', upload_to='uploads/'),
        ),
    ]
