# Generated by Django 4.1.7 on 2023-05-28 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=100)),
                ('ano_lancamento', models.IntegerField()),
                ('estado', models.CharField(max_length=100)),
                ('paginas', models.IntegerField()),
                ('editora', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Livros',
        ),
    ]
