# Generated by Django 4.1.7 on 2023-05-28 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0002_livro_delete_livros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
